### ISSUE TITLE
改善更新按鈕狀態與訂閱/發布成功失敗提示

### ISSUE THREAD

**Issue by guyleaf** [guyleaf/AWS_IoT_DH11_example#2]
* Websocket 連線按鈕狀態不一致
* 當未輸入 topic / range 時，訂閱/發布按紐需灰底
* 訂閱/發布成功失敗提示於介面底部

**Comment by zaqNitori** [comment]
> * Websocket 連線按鈕狀態不一致
> * 當未輸入 topic / range 時，訂閱/發布按紐需灰底
> * 訂閱/發布成功失敗提示於介面底部

1.按鈕狀態disconnect/connect切換太快，會有問題出現在(Connecting...階段)
2.未輸入把灰底，改成toast警告，並且不會做Subscribe或publish
3.在底部顯示狀態

**Comment by guyleaf** [comment]
@zaqNitori sub/pub按鈕，應在Connected時才變白底，Connecting 應還在灰底

**Comment by zaqNitori** [comment]
OK我改一下

**Comment by guyleaf** [comment]
@zaqNitori
pub 按鈕送出時，未檢查 topic 是否為空

**Comment by guyleaf** [comment]
@zaqNitori 
提示字體應用較顯眼之字體/顏色

**Comment by zaqNitori** [comment]
@guyleaf 我還需要PR一次?

**Comment by guyleaf** [comment]
不需要

**Comment by zaqNitori** [comment]
再試一次
textSize改成35dp
顏色調成 #ff0000

**Comment by zaqNitori** [comment]
@guyleaf  Subscribe內容的部分我測不到
再給你處理
History的部分應該也不會有意外發生

**Comment by guyleaf** [comment]
@zaqNitori 
Subscribe 未提示訂閱成功

**Comment by zaqNitori** [comment]
> @zaqNitori
> Subscribe 未提示訂閱成功

Publish的有嗎?
我這裡怎麼測都是fail 
我不確定

**Comment by guyleaf** [comment]
publish 有

**Comment by zaqNitori** [comment]
@guyleaf 我讓所有狀態都顯示
然後Subscribe是包錯位置，所以抓不到

**Comment by guyleaf** [comment]
@zaqNitori 在手機上輸入topic後，按其他地方鍵盤會自動消失嗎？因為模擬器會一直顯示，要手動按才消失

**Comment by guyleaf** [comment]
@zaqNitori 感測器初始數值改成用N/A好了
像這樣 humidity: N/A %

**Comment by zaqNitori** [comment]
@guyleaf  鍵盤的問題我試試看按下button隱藏他(不過android的這部分好像有問題)
N/A等等改

**Comment by zaqNitori** [comment]
@guyleaf 現在按button可以取消掉keyboard
不過你在輸入publish的topic name時會擋掉Publish button
所以我就寫一個hide keyboard放在中間，只拿來處理keyboard不會觸發其他任何動作
其他button也可以正常關閉keyboard，不過他們都會觸發事件，所以不太好

**Comment by guyleaf** [comment]
@zaqNitori 如果用座標判斷呢?

**Comment by zaqNitori** [comment]
這樣沒有辦法判斷是哪個event

**Comment by guyleaf** [comment]
那就先這樣了
